name: Deploy Enhanced LLM Playground

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test || true
      
    # Example for deploying to a VPS using SSH
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /path/to/enhanced-llm-playground
          git pull
          npm ci
          pm2 restart server.js || pm2 start server.js
    
    # Alternatively, deploy to Render or another cloud platform
    # - name: Deploy to Render
    #  run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}